// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFeuX9eYS90soHcdVRPtCXin6xGzwkSU',
    appId: '1:318302649937:web:0ad0712df2c32811310270',
    messagingSenderId: '318302649937',
    projectId: 'flutter-firebase-e26d8',
    authDomain: 'flutter-firebase-e26d8.firebaseapp.com',
    storageBucket: 'flutter-firebase-e26d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjVz8MsKgN_yJ9wVwUjlcpzueb-BZueI',
    appId: '1:318302649937:android:e83b49f2fc4e7f64310270',
    messagingSenderId: '318302649937',
    projectId: 'flutter-firebase-e26d8',
    storageBucket: 'flutter-firebase-e26d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6W8ZhqIoMcceYedj4Uge1EKwSMlFcRg',
    appId: '1:318302649937:ios:7fbfbd7848696cad310270',
    messagingSenderId: '318302649937',
    projectId: 'flutter-firebase-e26d8',
    storageBucket: 'flutter-firebase-e26d8.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6W8ZhqIoMcceYedj4Uge1EKwSMlFcRg',
    appId: '1:318302649937:ios:7fbfbd7848696cad310270',
    messagingSenderId: '318302649937',
    projectId: 'flutter-firebase-e26d8',
    storageBucket: 'flutter-firebase-e26d8.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTFeuX9eYS90soHcdVRPtCXin6xGzwkSU',
    appId: '1:318302649937:web:a476887fe2ee506b310270',
    messagingSenderId: '318302649937',
    projectId: 'flutter-firebase-e26d8',
    authDomain: 'flutter-firebase-e26d8.firebaseapp.com',
    storageBucket: 'flutter-firebase-e26d8.firebasestorage.app',
  );
}
